# GitHub Pages Configuration
title: "Ram Erlikh - Portfolio"
description: "Full-stack developer and tech enthusiast"
author: "Ram Erlikh"
url: "https://ramerlikh.com"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - "*.py"
  - "*.log"
  - "*_backup*"
  - README.md
  - .gitignore

# Include files
include:
  - assets/
  - CNAME
